# Generated by Django 3.0.6 on 2020-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='message',
            field=models.CharField(default='Nuovo ordine ricevuto', max_length=300),
            preserve_default=False,
        ),
    ]
