# Generated by Django 3.0.6 on 2020-05-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200512_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernotification',
            old_name='sender',
            new_name='order',
        ),
    ]
