# Generated by Django 3.0.6 on 2020-05-12 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200512_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='issued',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
