# Generated by Django 3.0.6 on 2020-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordernotification_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='status',
            field=models.CharField(choices=[('U', 'Unread'), ('R', 'Read')], default='U', max_length=1),
        ),
    ]
