# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:

  test-backend:

    docker:
      - image: circleci/python:3.8
    working_directory: ~/marette_backend

    steps:
      - checkout:
          path: ~/marette_backend

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Execute tests
          command: |
            . venv/bin/activate
            python3 manage.py test

# Orchestrate or schedule a set of jobs
workflows:

    main:
    # Run the welcome/run job in its own container
      jobs:
        - test-backend