# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

version: 2.1
jobs:

  test-backend:
    
    docker:
      - image: circleci/python:3.8
    working_directory: ~/marette_backend

    steps:
      - checkout:
          path: ~/marette_backend

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            
      - run:
          name: Database Makemigrations
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations
            
      - run:
          name: Database Migrate
          command: |
            . venv/bin/activate
            python3 manage.py migrate
            
      - run:
          name: Execute tests
          command: |
            . venv/bin/activate
            python3 manage.py test

# Orchestrate or schedule a set of jobs
workflows:

    main:
    # Run the welcome/run job in its own container
      jobs:
        - test-backend:
            filters:
              branches:
                only:
                  - deploy
        - aws-code-deploy/deploy:
            application-name: marette-deploy
            bundle-bucket: marette-deploy
            arguments: '--file-exists-behavior "OVERWRITE"'
            bundle-key: v2
            deployment-group: main-deploy-group
            service-role-arn: arn:aws:iam::685988842947:role/CodeDeployServiceRole
         
