# Generated by Django 3.0.4 on 2020-03-25 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('cellphone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Please insert a valid cellphone number', regex='^(\\+\\d{2}){0,1}3{1}\\d{9}$')])),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30, unique=True)),
                ('activity_name', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('cap', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='[0-9]{5}')])),
                ('business_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Please insert a valid cellphone number', regex='^(\\+\\d{2}){0,1}3{1}\\d{9}$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
