# Generated by Django 3.0.4 on 2020-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='birth_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
