# Generated by Django 3.0.4 on 2020-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='n_civ',
            field=models.IntegerField(null=True),
        ),
    ]
