# Generated by Django 3.0.4 on 2020-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200426_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='n_civ',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
