# Generated by Django 3.0.4 on 2020-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200404_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='business',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
