# Generated by Django 3.0.4 on 2020-05-08 08:23

import backend.account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200426_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=95, size=[250, 250], upload_to=backend.account.models.content_file_name),
        ),
    ]
