# Generated by Django 3.0.4 on 2020-04-03 09:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200403_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None, unique=True),
        ),
    ]
