# Generated by Django 3.0.4 on 2020-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200404_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cf',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
