# Generated by Django 3.0.6 on 2020-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_business_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='activation_token',
            field=models.CharField(default='akjdlkndoieedjijdwoedjw', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='activation_token',
            field=models.CharField(default='skjdi0jdepodjepwdjweqdjpeqw', max_length=200),
            preserve_default=False,
        ),
    ]
