# Generated by Django 3.0.4 on 2020-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200403_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='activity_name',
            field=models.CharField(max_length=30),
        ),
    ]
