# Generated by Django 3.0.4 on 2020-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200404_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='birth_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
