# Generated by Django 3.0.4 on 2020-04-05 12:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200404_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Esiste già un utente con questo numero.'}, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Esiste già un utente con questo numero.'}, max_length=128, region=None, unique=True),
        ),
    ]
