# Generated by Django 3.0.6 on 2020-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200520_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='activation_token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='activation_token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
