# Generated by Django 3.0.6 on 2020-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200520_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='n_civ',
            field=models.CharField(max_length=10),
        ),
    ]
