# Generated by Django 3.0.4 on 2020-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200405_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email_activated',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_activated',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
