# Generated by Django 3.0.4 on 2020-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
