# Generated by Django 3.0.4 on 2020-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customervote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customervote',
            constraint=models.UniqueConstraint(fields=('customer', 'restaurant'), name='unique_vote_for_user_at_rest'),
        ),
    ]
