# Generated by Django 3.0.4 on 2020-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='n_civ',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
