# Generated by Django 3.0.4 on 2020-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='p_iva',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
