# Generated by Django 3.0.4 on 2020-05-23 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200523_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.RegexValidator(regex='[0-5]{0}')]),
        ),
    ]
