# Generated by Django 3.0.4 on 2020-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200414_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
