# Generated by Django 3.0.4 on 2020-04-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200414_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Fisso', 'Fisso'), ('Percentuale', 'Percentuale')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Altro', 'Altro'), ('Antipasto', 'Antipasto'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Contorno', 'Contorno'), ('Dessert', 'Dessert'), ('Caffetteria', 'Caffetteria'), ('Panetteria', 'Panetteria'), ('Panini e Piadine', 'Panini e Piadine'), ('Pizza', 'Pizza'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Snack', 'Snack')], default='Altro', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounts', models.ManyToManyField(blank=True, to='webapp.ProductDiscount')),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='webapp.Restaurant')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='webapp.ProductTag')),
            ],
        ),
    ]
