# Generated by Django 3.0.4 on 2020-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_menu_product_productdiscount_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='webapp.ProductTag'),
        ),
    ]
