# Generated by Django 3.0.4 on 2020-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200426_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='products',
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ManyToManyField(to='webapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='entries',
            field=models.ManyToManyField(blank=True, to='webapp.MenuEntry'),
        ),
    ]
