# Generated by Django 3.0.4 on 2020-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200415_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
