# Generated by Django 3.0.4 on 2020-04-15 14:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_producttag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[32, 32], upload_to='C:\\Users\\Marco\\PycharmProjects\\marette_backend\\media'),
        ),
    ]
