# Generated by Django 3.0.4 on 2020-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200426_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_image',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
