# Generated by Django 3.0.4 on 2020-04-15 16:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200415_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ManyToManyField(blank=True, to='webapp.Menu'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='png', keep_meta=True, null=True, quality=0, size=[32, 32], upload_to='C:\\Users\\Marco\\PycharmProjects\\marette_backend\\media'),
        ),
    ]
