# Generated by Django 3.0.4 on 2020-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_product_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentry',
            name='num_products',
            field=models.IntegerField(default=1),
        ),
    ]
