# Generated by Django 3.0.4 on 2020-05-23 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200523_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervote',
            name='vote',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^([0-5])$')]),
        ),
    ]
