# Generated by Django 3.0.4 on 2020-04-27 09:42

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200427_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='num_products',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
