# Generated by Django 3.0.4 on 2020-05-23 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200523_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervote',
            name='vote',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
