# Generated by Django 3.0.4 on 2020-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200415_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(blank=True, to='webapp.Product'),
        ),
        migrations.DeleteModel(
            name='MenuEntry',
        ),
    ]
