# Generated by Django 3.0.4 on 2020-05-23 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200523_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
