# Generated by Django 3.0.4 on 2020-04-27 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200427_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='num_products',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cap',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='[0-9]{5}')]),
        ),
    ]
