# Generated by Django 3.0.4 on 2020-04-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200415_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'restaurant': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Restaurant')}, to='webapp.Product'),
        ),
    ]
