# Generated by Django 3.0.4 on 2020-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200427_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='n_civ',
            field=models.PositiveIntegerField(),
        ),
    ]
