# Generated by Django 3.0.4 on 2020-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_restaurant_customer_vote_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='customer_vote_list',
            field=models.ManyToManyField(blank=True, related_name='customer_vote_list', to='webapp.CustomerVote'),
        ),
    ]
