# Generated by Django 3.0.4 on 2020-04-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200427_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home', 'Home'), ('Vetrina', 'Vetrina'), ('Menù', 'Menù'), ('Galleria', 'Galleria'), ('Contattaci', 'Contattaci'), ('Eventi', 'Eventi')], max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(blank=True, to='webapp.Component')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='webapp.Restaurant')),
            ],
        ),
    ]
