# Generated by Django 3.0.4 on 2020-04-15 19:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200415_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Altro', 'Altro'), ('Antipasto', 'Antipasto'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Contorno', 'Contorno'), ('Dessert', 'Dessert'), ('Caffetteria', 'Caffetteria'), ('Panetteria', 'Panetteria'), ('Panini e Piadine', 'Panini e Piadine'), ('Pizza', 'Pizza'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Snack', 'Snack')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(to='webapp.ProductDiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Marco\\PycharmProjects\\marette_backend\\public\\media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='webapp.ProductTag'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='png', keep_meta=True, null=True, quality=0, size=[32, 32], upload_to='C:\\Users\\Marco\\PycharmProjects\\marette_backend\\public\\media'),
        ),
    ]
