# Generated by Django 3.0.4 on 2020-04-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_component_restaurantcomponents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='active',
        ),
    ]
