# Generated by Django 3.0.4 on 2020-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_component_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(choices=[('Home', 'Home'), ('Vetrina', 'Vetrina'), ('Menù', 'Menù'), ('Galleria', 'Galleria'), ('Contattaci', 'Contattaci'), ('Eventi', 'Eventi')], max_length=100, unique=True),
        ),
    ]
