# Generated by Django 3.0.4 on 2020-04-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200415_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_discount', to='webapp.Restaurant'),
            preserve_default=False,
        ),
    ]
