# Generated by Django 3.0.4 on 2020-04-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200429_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='webapp.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(choices=[('Home', 'Home'), ('Vetrina', 'Vetrina'), ('Menù', 'Menù'), ('Galleria', 'Galleria'), ('Contattaci', 'Contattaci'), ('Eventi', 'Eventi')], max_length=100),
        ),
    ]
