# Generated by Django 3.0.4 on 2020-04-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200429_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('restaurant', 'name')},
        ),
    ]
