# Generated by Django 3.0.4 on 2020-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200429_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventicomponent',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleriacomponent',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecomponent',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menucomponent',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vetrinacomponent',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
