# Generated by Django 3.0.4 on 2020-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20200429_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventicomponent',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleriacomponent',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homecomponent',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menucomponent',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vetrinacomponent',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
