# Generated by Django 3.0.4 on 2020-04-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200429_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContattaciComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contattaci_component', to='webapp.Restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='restaurantcomponents',
            name='contattaci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contattaci_component', to='webapp.ContattaciComponent'),
        ),
    ]
