# Generated by Django 3.0.4 on 2020-05-01 12:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20200429_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecomponent',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='components/home'),
        ),
    ]
