# Generated by Django 3.0.4 on 2020-05-01 12:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_homecomponent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecomponent',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=90, size=[1920, 1080], upload_to='components/home'),
        ),
    ]
