# Generated by Django 3.0.4 on 2020-05-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20200501_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetrinacomponent',
            name='menu_giorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_giorno', to='webapp.Menu'),
        ),
    ]
