# Generated by Django 3.0.4 on 2020-05-01 14:04

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_vetrinacomponent_menu_giorno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=95, size=[600, 600], upload_to='components/gallery')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='galleriacomponent',
            name='immagini',
            field=models.ManyToManyField(blank=True, null=True, related_name='immagini', to='webapp.Picture'),
        ),
    ]
