# Generated by Django 3.0.4 on 2020-05-01 14:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20200501_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=False, quality=95, size=[600, 600], upload_to='components/gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
