# Generated by Django 3.0.4 on 2020-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20200501_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleriacomponent',
            name='immagini',
            field=models.ManyToManyField(blank=True, related_name='immagini', to='webapp.Picture'),
        ),
    ]
