# Generated by Django 3.0.4 on 2020-05-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_auto_20200503_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='webapp.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menus_items',
            field=models.ManyToManyField(blank=True, to='webapp.Menu'),
        ),
    ]
