# Generated by Django 3.0.4 on 2020-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20200503_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
