# Generated by Django 3.0.4 on 2020-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_auto_20200504_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
