# Generated by Django 3.0.4 on 2020-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
