# Generated by Django 3.0.4 on 2020-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_auto_20200504_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
