# Generated by Django 3.0.4 on 2020-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_auto_20200506_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdiscount',
            name='category',
            field=models.CharField(choices=[('Altro', 'Altro'), ('Antipasto', 'Antipasto'), ('Contorno', 'Contorno'), ('Dessert', 'Dessert'), ('Caffetteria', 'Caffetteria'), ('Panetteria', 'Panetteria'), ('Panini e Piadine', 'Panini e Piadine'), ('Pizza', 'Pizza'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Snack', 'Snack'), ('All', 'All')], default='Altro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantdiscount',
            name='type',
            field=models.CharField(choices=[('Fisso', 'Fisso'), ('Percentuale', 'Percentuale')], max_length=30),
        ),
    ]
