# Generated by Django 3.0.4 on 2020-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_auto_20200506_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='rest_discounts', to='webapp.RestaurantDiscount'),
        ),
    ]
