# Generated by Django 3.0.4 on 2020-05-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_restaurant_discounts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantdiscount',
            unique_together={('restaurant', 'title', 'type', 'category', 'value')},
        ),
    ]
