# Generated by Django 3.0.4 on 2020-05-06 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_auto_20200506_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
