# Generated by Django 3.0.4 on 2020-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200426_1615'),
        ('webapp', '0061_auto_20200507_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='p_iva',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('id', 'owner', 'p_iva')},
        ),
    ]
