# Generated by Django 3.0.4 on 2020-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0062_auto_20200507_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
