# Generated by Django 3.0.4 on 2020-05-08 10:18

import backend.webapp.models.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_auto_20200508_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=95, size=[600, 600], upload_to=backend.webapp.models.models.gallery_component),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.webapp.models.models.products_image),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.webapp.models.models.products_image_thumb),
        ),
    ]
