# Generated by Django 3.0.4 on 2020-05-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_auto_20200508_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='entries',
        ),
        migrations.AddField(
            model_name='menuentry',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Menu'),
            preserve_default=False,
        ),
    ]
