# Generated by Django 3.0.6 on 2020-05-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_auto_20200512_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='webapp.Restaurant'),
            preserve_default=False,
        ),
    ]
