# Generated by Django 3.0.6 on 2020-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_picture_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleriacomponent',
            name='immagini',
        ),
    ]
